package me.bmax.apatch.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val win98_light_background = Color(0xFFC0C0C0)
private val win98_light_surface = Color(0xFFC0C0C0)
private val win98_light_surface_variant = Color(0xFFFFFFFF)
private val win98_light_onSurface = Color(0xFF000000)
private val win98_light_onBackground = Color(0xFF000000)
private val win98_light_onSurfaceVariant = Color(0xFF000000)
private val win98_light_primary = Color(0xFF000080)
private val win98_light_onPrimary = Color(0xFFFFFFFF)
private val win98_light_primaryContainer = Color(0xFF000080)
private val win98_light_onPrimaryContainer = Color(0xFFFFFFFF)
private val win98_light_secondary = Color(0xFF808080)
private val win98_light_onSecondary = Color(0xFF000000)
private val win98_light_secondaryContainer = Color(0xFFC0C0C0)
private val win98_light_onSecondaryContainer = Color(0xFF000000)
private val win98_light_tertiary = Color(0xFF000080)
private val win98_light_onTertiary = Color(0xFFFFFFFF)
private val win98_light_tertiaryContainer = Color(0xFFC0C0C0)
private val win98_light_onTertiaryContainer = Color(0xFF000000)
private val win98_light_error = Color(0xFF000080)
private val win98_light_errorContainer = Color(0xFFC0C0C0)
private val win98_light_onError = Color(0xFFFFFFFF)
private val win98_light_onErrorContainer = Color(0xFF000000)
private val win98_light_outline = Color(0xFF000000)
private val win98_light_outlineVariant = Color(0xFF808080)
private val win98_light_inverseOnSurface = Color(0xFFFFFFFF)
private val win98_light_inverseSurface = Color(0xFF000080)
private val win98_light_inversePrimary = Color(0xFFFF8000)
private val win98_light_surfaceTint = Color(0xFF000080)
private val win98_light_scrim = Color(0xFF000000)
private val win98_light_shadow = Color(0xFF000000)

private val win98_dark_background = Color(0xFF000080)
private val win98_dark_surface = Color(0xFF000080)
private val win98_dark_surface_variant = Color(0xFF000000)
private val win98_dark_onSurface = Color(0xFFFFFFFF)
private val win98_dark_onBackground = Color(0xFFC0C0C0)
private val win98_dark_onSurfaceVariant = Color(0xFFC0C0C0)
private val win98_dark_primary = Color(0xFFFF8000)
private val win98_dark_onPrimary = Color(0xFF000000)
private val win98_dark_primaryContainer = Color(0xFFFF8000)
private val win98_dark_onPrimaryContainer = Color(0xFF000000)
private val win98_dark_secondary = Color(0xFF808080)
private val win98_dark_onSecondary = Color(0xFF000000)
private val win98_dark_secondaryContainer = Color(0xFF404040)
private val win98_dark_onSecondaryContainer = Color(0xFFC0C0C0)
private val win98_dark_tertiary = Color(0xFFFF8000)
private val win98_dark_onTertiary = Color(0xFF000000)
private val win98_dark_tertiaryContainer = Color(0xFF404040)
private val win98_dark_onTertiaryContainer = Color(0xFFC0C0C0)
private val win98_dark_error = Color(0xFFFF0000)
private val win98_dark_errorContainer = Color(0xFF404040)
private val win98_dark_onError = Color(0xFFFFFFFF)
private val win98_dark_onErrorContainer = Color(0xFFFF0000)
private val win98_dark_outline = Color(0xFFC0C0C0)
private val win98_dark_outlineVariant = Color(0xFF808080)
private val win98_dark_inverseOnSurface = Color(0xFF000000)
private val win98_dark_inverseSurface = Color(0xFFC0C0C0)
private val win98_dark_inversePrimary = Color(0xFF000080)
private val win98_dark_surfaceTint = Color(0xFFFF8000)
private val win98_dark_scrim = Color(0xFF000000)
private val win98_dark_shadow = Color(0xFF000000)

val LightWin98Theme = lightColorScheme(
    primary = win98_light_primary,
    onPrimary = win98_light_onPrimary,
    primaryContainer = win98_light_primaryContainer,
    onPrimaryContainer = win98_light_onPrimaryContainer,
    secondary = win98_light_secondary,
    onSecondary = win98_light_onSecondary,
    secondaryContainer = win98_light_secondaryContainer,
    onSecondaryContainer = win98_light_onSecondaryContainer,
    tertiary = win98_light_tertiary,
    onTertiary = win98_light_onTertiary,
    tertiaryContainer = win98_light_tertiaryContainer,
    onTertiaryContainer = win98_light_onTertiaryContainer,
    error = win98_light_error,
    errorContainer = win98_light_errorContainer,
    onError = win98_light_onError,
    onErrorContainer = win98_light_onErrorContainer,
    background = win98_light_background,
    onBackground = win98_light_onBackground,
    surface = win98_light_surface,
    onSurface = win98_light_onSurface,
    surfaceVariant = win98_light_surface_variant,
    onSurfaceVariant = win98_light_onSurfaceVariant,
    outline = win98_light_outline,
    inverseOnSurface = win98_light_inverseOnSurface,
    inverseSurface = win98_light_inverseSurface,
    inversePrimary = win98_light_inversePrimary,
    surfaceTint = win98_light_surfaceTint,
    outlineVariant = win98_light_outlineVariant,
    scrim = win98_light_scrim,
)

val DarkWin98Theme = darkColorScheme(
    primary = win98_dark_primary,
    onPrimary = win98_dark_onPrimary,
    primaryContainer = win98_dark_primaryContainer,
    onPrimaryContainer = win98_dark_onPrimaryContainer,
    secondary = win98_dark_secondary,
    onSecondary = win98_dark_onSecondary,
    secondaryContainer = win98_dark_secondaryContainer,
    onSecondaryContainer = win98_dark_onSecondaryContainer,
    tertiary = win98_dark_tertiary,
    onTertiary = win98_dark_onTertiary,
    tertiaryContainer = win98_dark_tertiaryContainer,
    onTertiaryContainer = win98_dark_onTertiaryContainer,
    error = win98_dark_error,
    errorContainer = win98_dark_errorContainer,
    onError = win98_dark_onError,
    onErrorContainer = win98_dark_onErrorContainer,
    background = win98_dark_background,
    onBackground = win98_dark_onBackground,
    surface = win98_dark_surface,
    onSurface = win98_dark_onSurface,
    surfaceVariant = win98_dark_surface_variant,
    onSurfaceVariant = win98_dark_onSurfaceVariant,
    outline = win98_dark_outline,
    inverseOnSurface = win98_dark_inverseOnSurface,
    inverseSurface = win98_dark_inverseSurface,
    inversePrimary = win98_dark_inversePrimary,
    surfaceTint = win98_dark_surfaceTint,
    outlineVariant = win98_dark_outlineVariant,
    scrim = win98_dark_scrim,
)